### ISSUE TITLE
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired

### ISSUE THREAD

**Issue by eliassal** [robrich/database-devops-with-containers#1]
Hi Rob, I attended your session today, very interesting and useful. I followed all steps, I ran the following command on  a Centos 7 box

`docker build -t dev-database .`
I get

> Step 6/10 : COPY prod-to-dev.sql .
>  ---> eba596bd26d4
> Step 7/10 : RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 80     && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P SecureP@ssw0rd -i /tmp/prod-to-dev.sql     && pkill sqlservr
>  ---> Running in 9c0fb101fc69
> 2020-04-01 16:43:24.58 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
> .....
> ......
> ......
> ....
> 2020-04-01 16:44:22.47 spid6s      The tail of the log for database master is being rewritten to match the new sector size of 4096 bytes.  3072 bytes at offset 418816 in file /var/opt/mssql/data/mastlog.ldf will be written.
> 2020-04-01 16:44:23.91 spid6s      Recovery completed for database master (database ID 1) in 2 second(s) (analysis 226 ms, redo 156 ms, undo 59 ms.) This is an informational message only. No user action is required.
> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login timeout expired.
> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2749.                                
> Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..                 
> The command '/bin/sh -c /opt/mssql/bin/sqlservr --accept-eula & sleep 80     && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P SecureP@ssw0rd -i /tmp/prod-to-dev.sql     && pkill sqlservr' returned a non-zero code: 1
> 

when I do
`docker imgaes`
I get

![poshgit_002](https://user-images.githubusercontent.com/8447864/78167629-11514a80-744f-11ea-929a-04646b2129ea.jpg)

 
Thanks for your help

**Comment by robrich** [comment]
I get this when my Docker environment is overloaded.  Try going into Docker settings and upping the RAM to 4 gigs.

**Comment by eliassal** [comment]
Correct, my Centos boz RAM usage was 80%, I rebooted and you image build went through and I was able to run a container and access the sql from ssms. However, I used "sa" as the login and thought that the password was changed from "SecureP@ssw0rd" to 'D3vP@ssw0rd'
by the statement
`ALTER LOGIN SA WITH PASSWORD='D3vP@ssw0rd' `in file prod-to-dev.sql

'D3vP@ssw0rd' did not work, I used "SecureP@ssw0rd"  and was able to logon, I am a little bit confused :-)

**Comment by eliassal** [comment]
Also, AppUser is missing in the container Database Webapp which is in the other sql before I did the backup, its default DB is this webapp DB.
Even after creating the user with password = production, I get

> System.Data.SqlClient.SqlException: 'Cannot open database "WebApp" requested by the login. The login failed.
> Login failed for user 'AppUser'.'

I created manuly the user in the container, granted him Read/write on the DB in the container, when I run the webapp, I get the following error (of course webapp DB is empty), I get an error on line 32 in HomeController

> System.InvalidOperationException: 'Sequence contains no elements'

![devopssql](https://user-images.githubusercontent.com/8447864/78189358-2be8eb00-7472-11ea-8935-b678f14e5d4c.jpg)

**Comment by eliassal** [comment]
Rob, I managed finally by making the web app works , I generated fake data (5000 rows in each table). However, there is always an issue with the scripts and the user AppUser, first, after running the container and going through "Logins" in security on SQL level, it is not there, it exists only on the database level but Read/Write are stripped, it can't access the database.
I added the following

```
CREATE LOGIN [AppUser] WITH PASSWORD=N'production', DEFAULT_DATABASE=[WebApp], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
```
to the sql script file called by the creation, rerun the build and container, I can see user in SQL and in the DB in the container but can't access the DB as again Read/Write were stripped, I needed to run the following in the container


```
USE [WebApp]
GO
ALTER ROLE [db_datareader] ADD MEMBER [AppUser]
GO
USE [WebApp]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [AppUser]
GO

```
as well as as I said earlier, password is still 'production' in spite of the successful execution of
```
EXEC sp_change_users_login 'Auto_Fix', 'AppUser', NULL, 'D3vP@ssw0rd'
GO
```

**Comment by robrich** [comment]
Good call.  I haven't kept the site up to date.  Want to send a PR with these changes?

**Comment by eliassal** [comment]
OK, but how? I went to create PR, it asks to do it in a new branch, I think I am not authorized to create a new branch

**Comment by eliassal** [comment]
Well, as I have nebver used PR on Git, I forked to my git and created a PR at
https://github.com/robrich/database-devops-with-containers/pull/2
is this what you need?

**Comment by robrich** [comment]
Thanks for the PR. I merged it some time ago and forgot to close this issue.
